# Site settings
title: Adelante Landscapes
email: cbeesley1717@gmail.com
description: >-
  Professional landscape design in North Texas specializing in edible gardens, native plants, and sustainable landscaping. 
  Serving Dallas, Fort Worth, Plano, and surrounding areas with 30+ years of experience.
baseurl: ""
url: "https://adelantelandscapes.com"

# SEO settings
author: "Cheryl Beesley"
logo: "/assets/images/Logo.jpg"
social:
  name: "Adelante Landscapes"
  links:
    - "https://adelantelandscapes.com"

# Location information for local SEO
location:
  name: "North Texas"
  region: "Texas"
  country: "US"
  phone: "(682)225-3486"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/

# Plugins - only use GitHub Pages supported plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# GitHub Pages settings
remote_theme: null
theme: null

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - local-*.html
  - README.md

# Include files
include:
  - _pages

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Collections
collections:
  projects:
    output: true
    permalink: /portfolio/:name/

# Site data
author:
  name: Cheryl Beesley
  bio: >-
    Landscape designer and visionary with over 30 years of experience.
    Master's degree in landscape architecture with focus in horticulture
    and environmental sustainability.
  phone: (682)225-3486
  location: Fort Worth, Texas 76112

# Social links
social:
  facebook: https://www.facebook.com/adelantelandscape
  linkedin: https://www.linkedin.com/in/cheryl-beesley-399125a4/

# Navigation - Updated to match actual file structure
navigation:
  - title: Home
    url: /
  - title: About
    url: /about.html
  - title: Services
    url: /services.html
  - title: Portfolio
    url: /portfolio.html
  - title: Blog
    url: /blog.html
  - title: Contact
    url: /contact.html
